### ISSUE TITLE
Feature- mock or sample images

### ISSUE THREAD

**Issue by duncdrum** [hcts-hra/iipsrv-ecpo#2]
I think it would be a good idea to have a small sample of images to live along side the docker files to mount with the container for quick testing and developing. 

what would make sense here, just some (2, 20, 10?) full size images, a mix of file formats, downsized images (of the whole db…)

**Comment by JoeTo1** [comment]
Added. see playground documentation:

https://github.com/JoeTo1/iipsrv-ecpo/blob/develop-docker/playground/documentation.md
